"""Seed cafe data for first-run demos.

These cafes give the app useful content before anyone imports Google Places
results. The database inserts them only when their cafe_id does not exist yet.
"""

SEED_CAFES = [
    {
        "cafe_id": "cafe-001",
        "google_place_id": None,
        "name": "Amber Roast",
        "area": "大安",
        "address": "台北市大安區和平東路一段 88 號",
        "distance_meters": 350,
        "lat": 25.0261,
        "lng": 121.5317,
        "rating": 4.8,
        "tags": ["手沖", "安靜", "插座", "適合讀書"],
        "description": "適合讀書和小組討論，手沖咖啡選項多。",
        "opening_hours": "週一至週日 09:00-20:00",
        "website": "",
        "maps_url": "https://www.google.com/maps/search/?api=1&query=Amber%20Roast%20Taipei",
    },
    {
        "cafe_id": "cafe-002",
        "google_place_id": None,
        "name": "Daily Grind",
        "area": "信義",
        "address": "台北市信義區松仁路 120 號",
        "distance_meters": 800,
        "lat": 25.0364,
        "lng": 121.5686,
        "rating": 4.5,
        "tags": ["拿鐵", "甜點", "交通方便", "適合聊天"],
        "description": "甜點和拿鐵表現穩定，靠近捷運站。",
        "opening_hours": "週一至週日 08:30-21:00",
        "website": "",
        "maps_url": "https://www.google.com/maps/search/?api=1&query=Daily%20Grind%20Taipei",
    },
    {
        "cafe_id": "cafe-003",
        "google_place_id": None,
        "name": "Quiet Cup",
        "area": "中山",
        "address": "台北市中山區南京東路二段 16 號",
        "distance_meters": 1200,
        "lat": 25.0522,
        "lng": 121.5281,
        "rating": 4.7,
        "tags": ["不限時", "安靜", "單人座", "適合讀書"],
        "description": "座位規劃舒服，不限時，適合完成作業。",
        "opening_hours": "週二至週日 10:00-19:30",
        "website": "",
        "maps_url": "https://www.google.com/maps/search/?api=1&query=Quiet%20Cup%20Taipei",
    },
    {
        "cafe_id": "cafe-004",
        "google_place_id": None,
        "name": "Bean Trail",
        "area": "公館",
        "address": "台北市中正區羅斯福路四段 24 巷 5 號",
        "distance_meters": 600,
        "lat": 25.0146,
        "lng": 121.5345,
        "rating": 4.3,
        "tags": ["學生友善", "平價", "外帶", "插座"],
        "description": "價格親民，適合學生課後買咖啡。",
        "opening_hours": "週一至週五 08:00-18:00",
        "website": "",
        "maps_url": "https://www.google.com/maps/search/?api=1&query=Bean%20Trail%20Taipei",
    },
    {
        "cafe_id": "cafe-005",
        "google_place_id": None,
        "name": "Moonlight Cafe",
        "area": "師大",
        "address": "台北市大安區師大路 45 號",
        "distance_meters": 950,
        "lat": 25.0243,
        "lng": 121.5294,
        "rating": 4.6,
        "tags": ["晚上營業", "甜點", "聚會", "適合聊天"],
        "description": "晚上也有營業，適合朋友聊天。",
        "opening_hours": "週一至週日 12:00-23:00",
        "website": "",
        "maps_url": "https://www.google.com/maps/search/?api=1&query=Moonlight%20Cafe%20Taipei",
    },
    {
        "cafe_id": "cafe-006",
        "google_place_id": None,
        "name": "Campus Beans",
        "area": "公館",
        "address": "台北市中正區汀州路三段 160 巷 2 號",
        "distance_meters": 450,
        "lat": 25.0152,
        "lng": 121.5322,
        "rating": 4.4,
        "tags": ["學生友善", "讀書", "插座", "不限時"],
        "description": "附近學生常去，座位多，適合小組討論。",
        "opening_hours": "週一至週六 09:00-21:00",
        "website": "",
        "maps_url": "https://www.google.com/maps/search/?api=1&query=Campus%20Beans%20Taipei",
    },
]
